---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPSMAN_ENV_FILE_NAME:
  PRODUCT_NAME:

inputs:
- name: pipelines-repo
- name: om-cli
- name: env
- name: pivnet-product

run:
  path: pipelines-repo/tasks/validate-apply-changes/task.sh
