---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  PIVNET_API_TOKEN:
  IAAS:
  IAAS_TYPE:
  STEMCELL_TYPE:

inputs:
- name: pivnet-product
- name: pipelines-repo
- name: pivnet-cli
- name: jq

outputs:
- name: stemcells

run:
  path: pipelines-repo/tasks/download-stemcell/task.sh
