---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:
  VCENTER_DISK_TYPE:
  STORAGE_NAMES:
  INFRA_NETWORK_NAME:
  INFRA_VCENTER_NETWORK:
  INFRA_NW_CIDR:
  INFRA_EXCLUDED_RANGE:
  INFRA_NW_DNS:
  INFRA_NW_GATEWAY:
  INFRA_NW_AZS:
  DEPLOYMENT_NETWORK_NAME:
  DEPLOYMENT_VCENTER_NETWORK:
  DEPLOYMENT_NW_CIDR:
  DEPLOYMENT_EXCLUDED_RANGE:
  DEPLOYMENT_NW_DNS:
  DEPLOYMENT_NW_GATEWAY:
  DEPLOYMENT_NW_AZS:
  SERVICES_NETWORK_NAME:
  SERVICES_VCENTER_NETWORK:
  SERVICES_NW_CIDR:
  SERVICES_EXCLUDED_RANGE:
  SERVICES_NW_DNS:
  SERVICES_NW_GATEWAY:
  SERVICES_NW_AZS:
  DYNAMIC_SERVICES_NETWORK_NAME:
  DYNAMIC_SERVICES_VCENTER_NETWORK:
  DYNAMIC_SERVICES_NW_CIDR:
  DYNAMIC_SERVICES_EXCLUDED_RANGE:
  DYNAMIC_SERVICES_NW_DNS:
  DYNAMIC_SERVICES_NW_GATEWAY:
  DYNAMIC_SERVICES_NW_AZS:
  AZ_1:
  AZ_1_CUSTER_NAME:
  AZ_1_RP_NAME:
  AZ_2:
  AZ_2_CUSTER_NAME:
  AZ_2_RP_NAME:
  AZ_3:
  AZ_3_CUSTER_NAME:
  AZ_3_RP_NAME:
  NTP_SERVER_IPS:
  OPS_DIR_HOSTNAME:

inputs:
  - name: concourse-vsphere
  - name: om-cli

run:
  path: concourse-vsphere/tasks/config-opsdir/task.sh
