---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:
  VCENTER_DISK_TYPE:
  EPHEMERAL_STORAGE_NAMES:
  PERSISTENT_STORAGE_NAMES:
  BOSH_VM_FOLDER:
  BOSH_TEMPLATES_FOLDER:
  BOSH_DISK_PATH:
  NSX_NETWORKING_ENABLED:
  NSX_ADDRESS:
  NSX_PASSWORD:
  NSX_USERNAME:
  NSX_CA_CERTIFICATE:
  SSL_VERIFICATION_ENABLED:
  NTP_SERVERS:
  ENABLE_VM_RESURRECTOR:
  METRICS_IP:
  OPENTSDB_IP:
  POST_DEPLOY_ENABLED:
  BOSH_RECREATE_ON_NEXT_DEPLOY:
  RETRY_BOSH_DEPLOYS:
  KEEP_UNREACHABLE_VMS:
  MAX_THREADS:
  DIRECTOR_WORKER_COUNT:
  OPS_DIR_HOSTNAME:
  PAGER_DUTY_ENABLED:
  PAGER_DUTY_SERVICE_KEY:
  PAGER_DUTY_HTTP_PROXY:
  HM_EMAIL_ENABLED:
  SMTP_HOST:
  SMTP_PORT:
  SMTP_DOMAIN:
  FROM_ADDRESS:
  RECIPIENTS_ADDRESS:
  SMTP_USER:
  SMTP_PASSWORD:
  SMTP_TLS_ENABLED:
  BLOBSTORE_TYPE:
  S3_ENDPOINT:
  S3_BUCKET_NAME:
  S3_ACCESS_KEY:
  S3_SECRET_KEY:
  S3_SIGNATURE_VERSION:
  DATABASE_TYPE:
  EXTERNAL_MYSQL_DB_HOST:
  EXTERNAL_MYSQL_DB_PORT:
  EXTERNAL_MYSQL_DB_USER:
  EXTERNAL_MYSQL_DB_PASSWORD:
  EXTERNAL_MYSQL_DB_DATABASE:
  SYSLOG_ENABLED:
  SYSLOG_ADDRESS:
  SYSLOG_PORT:
  SYSLOG_TRANSPORT_PROTOCOL:
  SYSLOG_TLS_ENABLED:
  SYSLOG_PERMITTED_PEER:
  SYSLOG_SSL_CA_CERTIFICATE:
  ICMP_CHECKS_ENABLED:
  INFRA_NETWORK_NAME:
  INFRA_VCENTER_NETWORK:
  INFRA_NW_CIDR:
  INFRA_EXCLUDED_RANGE:
  INFRA_NW_DNS:
  INFRA_NW_GATEWAY:
  INFRA_NW_AZS:
  DEPLOYMENT_NETWORK_NAME:
  DEPLOYMENT_VCENTER_NETWORK:
  DEPLOYMENT_NW_CIDR:
  DEPLOYMENT_EXCLUDED_RANGE:
  DEPLOYMENT_NW_DNS:
  DEPLOYMENT_NW_GATEWAY:
  DEPLOYMENT_NW_AZS:
  SERVICES_NETWORK_NAME:
  SERVICES_NW_IS_SERVICE_NW:
  SERVICES_VCENTER_NETWORK:
  SERVICES_NW_CIDR:
  SERVICES_EXCLUDED_RANGE:
  SERVICES_NW_DNS:
  SERVICES_NW_GATEWAY:
  SERVICES_NW_AZS:
  DYNAMIC_SERVICES_NETWORK_NAME:
  DYNAMIC_SERVICES_NW_IS_SERVICE_NW:
  DYNAMIC_SERVICES_VCENTER_NETWORK:
  DYNAMIC_SERVICES_NW_CIDR:
  DYNAMIC_SERVICES_EXCLUDED_RANGE:
  DYNAMIC_SERVICES_NW_DNS:
  DYNAMIC_SERVICES_NW_GATEWAY:
  DYNAMIC_SERVICES_NW_AZS:
  AZ_1:
  AZ_1_CUSTER_NAME:
  AZ_1_RP_NAME:
  AZ_2:
  AZ_2_CUSTER_NAME:
  AZ_2_RP_NAME:
  AZ_3:
  AZ_3_CUSTER_NAME:
  AZ_3_RP_NAME:
  TRUSTED_CERTIFICATES:
  GENERATE_VM_PASSWORDS:

inputs:
  - name: pipelines-repo
  - name: om-cli

run:
  path: pipelines-repo/tasks/config-opsdir/task.sh
