---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  PRODUCT_IDENTIFIER:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOB_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  MYSQL_MONITOR_EMAIL:
  MYSQL_LOGQUEUE_INSTANCE_COUNT:
  ELASTICSEARCH_LOGQUEUE_INSTANCE_COUNT:
  INGESTOR_INSTANCE_COUNT:
  ELASTICSEARCH_MASTER_INSTANCE_TYPE:
  ELASTICSEARCH_MASTER_INSTANCES:
  ELASTICSEARCH_MASTER_PERSISTENT_DISK_SIZE:
  ELASTICSEARCH_DATA_INSTANCE_TYPE:
  ELASTICSEARCH_DATA_INSTANCES:
  ELASTICSEARCH_DATA_PERSISTENT_DISK_SIZE:
  MYSQL_SERVER_INSTANCE_TYPE:
  MYSQL_SERVER_INSTANCES:
  MYSQL_SERVER_PERSISTENT_DISK_SIZE:
  MYSQL_PROXY_INSTANCE_TYPE:
  MYSQL_PROXY_INSTANCES:

inputs:
  - name: pipelines-repo
  - name: om-cli

run:
  path: pipelines-repo/tasks/config-pcf-metrics/task.sh
