---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  PRODUCT_NAME:
  MYSQL_ROADMIN_PASSWORD:
  MYSQL_SKIP_NAME_RESOLVE:
  PUSH_APPS_ELASTICSEARCH_LOGQUEUE_INSTANCE_COUNT:
  PUSH_APPS_INGESTOR_INSTANCE_COUNT:
  PUSH_APPS_LOGS_RETENTION_WINDOW:
  PUSH_APPS_METRICS_RETENTION_WINDOW:
  PUSH_APPS_MYSQL_LOGQUEUE_INSTANCE_COUNT:
  PUSH_APPS_SERVER_INSTANCE_COUNT:
  ELASTICSEARCH_MASTER_INSTANCES:
  ELASTICSEARCH_MASTER_INSTANCE_TYPE:
  ELASTICSEARCH_MASTER_PERSISTENT_DISK_MB:
  ELASTICSEARCH_DATA_INSTANCES:
  ELASTICSEARCH_DATA_INSTANCE_TYPE:
  ELASTICSEARCH_DATA_PERSISTENT_DISK_MB:
  REDIS_INSTANCES:
  REDIS_INSTANCE_TYPE:
  REDIS_PERSISTENT_DISK_MB:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-apm/task.sh
