---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  PRODUCT_IDENTIFIER:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOBS_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  SERVICES_NETWORK_NAME:
  SYSLOG_SELECTOR:
  SYSLOG_ADDRESS:
  SYSLOG_PORT:
  SYSLOG_TRANSPORT:
  SYSLOG_FORMAT:
  SYSLOG_PERMITTED_PEER:
  SYSLOG_CA_CERT:
  METRICS_POLLING_INTERVAL:
  SMALL_PLAN_SELECTOR:
  SMALL_PLAN_SELECTOR_NAME:
  SMALL_PLAN_SELECTOR_DESCRIPTION:
  SMALL_PLAN_SELECTOR_CF_SERVICE_ACCESS:
  SMALL_PLAN_SELECTOR_AZ_SINGLE_SELECT:
  SMALL_PLAN_SELECTOR_VM_TYPE:
  SMALL_PLAN_SELECTOR_DISK_SIZE:
  SMALL_PLAN_SELECTOR_TIMEOUT:
  SMALL_PLAN_SELECTOR_TCP_KEEPALIVE:
  SMALL_PLAN_SELECTOR_MAXCLIENTS:
  SMALL_PLAN_SELECTOR_LUA_SCRIPTING:
  SMALL_PLAN_SELECTOR_INSTANCE_LIMIT:
  MEDIUM_PLAN_SELECTOR:
  MEDIUM_PLAN_SELECTOR_NAME:
  MEDIUM_PLAN_SELECTOR_DESCRIPTION:
  MEDIUM_PLAN_SELECTOR_CF_SERVICE_ACCESS:
  MEDIUM_PLAN_SELECTOR_AZ_SINGLE_SELECT:
  MEDIUM_PLAN_SELECTOR_VM_TYPE:
  MEDIUM_PLAN_SELECTOR_DISK_SIZE:
  MEDIUM_PLAN_SELECTOR_TIMEOUT:
  MEDIUM_PLAN_SELECTOR_TCP_KEEPALIVE:
  MEDIUM_PLAN_SELECTOR_MAXCLIENTS:
  MEDIUM_PLAN_SELECTOR_LUA_SCRIPTING:
  MEDIUM_PLAN_SELECTOR_INSTANCE_LIMIT:
  LARGE_PLAN_SELECTOR:
  LARGE_PLAN_SELECTOR_NAME:
  LARGE_PLAN_SELECTOR_DESCRIPTION:
  LARGE_PLAN_SELECTOR_CF_SERVICE_ACCESS:
  LARGE_PLAN_SELECTOR_AZ_SINGLE_SELECT:
  LARGE_PLAN_SELECTOR_VM_TYPE:
  LARGE_PLAN_SELECTOR_DISK_SIZE:
  LARGE_PLAN_SELECTOR_TIMEOUT:
  LARGE_PLAN_SELECTOR_TCP_KEEPALIVE:
  LARGE_PLAN_SELECTOR_MAXCLIENTS:
  LARGE_PLAN_SELECTOR_LUA_SCRIPTING:
  LARGE_PLAN_SELECTOR_INSTANCE_LIMIT:
  BACKUPS_SELECTOR:
  BACKUPS_SELECTOR_S3_ACCESS_KEY_ID:
  BACKUPS_SELECTOR_S3_SECRET_ACCESS_KEY:
  BACKUPS_SELECTOR_S3_ENDPOINT_URL:
  BACKUPS_SELECTOR_S3_REGION:
  BACKUPS_SELECTOR_S3_SIGNATURE_VERSION:
  BACKUPS_SELECTOR_S3_BUCKET_NAME:
  BACKUPS_SELECTOR_S3_PATH:
  BACKUPS_SELECTOR_S3_CRON_SCHEDULE:
  BACKUPS_SELECTOR_S3_BG_SAVE_TIMEOUT:
  BACKUPS_SELECTOR_SCP_SERVER:
  BACKUPS_SELECTOR_SCP_USER:
  BACKUPS_SELECTOR_SCP_KEY:
  BACKUPS_SELECTOR_SCP_PATH:
  BACKUPS_SELECTOR_SCP_PORT:
  BACKUPS_SELECTOR_SCP_CRON_SCHEDULE:
  BACKUPS_SELECTOR_SCP_BG_SAVE_TIMEOUT:
  BACKUPS_SELECTOR_SCP_FINGERPRINT:
  BACKUPS_SELECTOR_AZURE_ACCOUNT:
  BACKUPS_SELECTOR_AZURE_STORAGE_ACCESS_KEY:
  BACKUPS_SELECTOR_AZURE_PATH:
  BACKUPS_SELECTOR_AZURE_CRON_SCHEDULE:
  BACKUPS_SELECTOR_AZURE_BG_SAVE_TIMEOUT:
  BACKUPS_SELECTOR_AZURE_CONTAINER:
  BACKUPS_SELECTOR_AZURE_BLOB_STORE_BASE_URL:
  BACKUPS_SELECTOR_GCS_PROJECT_ID:
  BACKUPS_SELECTOR_GCS_BUCKET_NAME:
  BACKUPS_SELECTOR_GCS_SERVICE_ACCOUNT_JSON:
  BACKUPS_SELECTOR_GCS_CRON_SCHEDULE:
  BACKUPS_SELECTOR_GCS_BG_SAVE_TIMEOUT:
  REDIS_ON_DEMAND_BROKER_SERVICE_INSTANCE_LIMIT:
  REDIS_ON_DEMAND_BROKER_VM_EXTENSIONS:
  CF_REDIS_BROKER_SERVICE_INSTANCE_LIMIT:
  CF_REDIS_BROKER_REDIS_MAXMEMORY:
  REDIS_ON_DEMAND_BROKER_INSTANCE_TYPE:
  REDIS_ON_DEMAND_BROKER_INSTANCES:
  REDIS_ON_DEMAND_BROKER_DISK_SIZE:
  CF_REDIS_BROKER_INSTANCE_TYPE:
  CF_REDIS_BROKER_INSTANCES:
  CF_REDIS_BROKER_DISK_SIZE:
  DEDICATED_NODE_INSTANCE_TYPE:
  DEDICATED_NODE_INSTANCES:
  DEDICATED_NODE_DISK_SIZE:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-redis/task.sh
