---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPSMAN_ENV_FILE_NAME:
  PRODUCT_NAME:
  DEPENDENCY_PRODUCT_TILES:

inputs:
- name: pipelines-repo
- name: om-cli
- name: pivnet-product
- name: env

run:
  path: pipelines-repo/tasks/stage-product/task.sh
