---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OM_TARGET:
  OM_USERNAME:
  OM_PASSWORD:
  OM_CLIENT_ID:
  OM_CLIENT_SECRET:
  PRODUCT_NAME:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq
  - name: tile-config-convertor

run:
  path: pipelines-repo/tasks/generate-config/task.sh
