---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PIVNET_API_TOKEN:
  IAAS_TYPE:
  STEMCELL_TYPE:

inputs:
  - name: pivnet-product
  - name: pipelines-repo
  - name: om-cli
  - name: pivnet-cli
  - name: jq

run:
  path: pipelines-repo/tasks/stemcell-uploader/task.sh
